version: '3.9'

services:
  postgres:
    image: postgres:14.0
    container_name: postgres
    environment:
      POSTGRES_DB: "task_tracker"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my-net
  app:
    image: maven:3-openjdk-16
    command: "mvn spring-boot:run"
    working_dir: /TaskTracker
    volumes:
      - ./:/TaskTracker
      - ~/.m2:/root/.m2
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/task_tracker"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "postgres"
    depends_on:
      - postgres
    ports:
      - "20000:20000"
    networks:
      - my-net

volumes:
  postgres-data:

networks:
  my-net: